# Generated by Django 4.0.6 on 2024-07-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='et',
            options={},
        ),
    ]
